[package]
name = "mesh_extras"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "*"}
glam = "*"
component_extras = { path = "../component_extras" }
camera_extras = {path = "../camera_extras"}

[lib]
crate-type=["lib"]